### ISSUE TITLE
Reg: LCD Display

### ISSUE THREAD

**Issue by bkannadassan** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#11]
Hi All,

  I see the LCD project (20) just switches on the LCD but I don't see any display on the same. Please let me know if there is any change to be done in the script..

-Balaji Kamal Kannadassan

**Comment by SuhaylZhao** [comment]
Hi,

There is a potentiometer on the back of LCD. You can change the contrast of LCD by adjusting the potentiometer. 

Thanks.

**Comment by bkannadassan** [comment]
You were bangon :-). I realized after going through the I2C and the same is working great. Thanks again..

**Comment by SuhaylZhao** [comment]
Great!

Please enjoy it.

Thanks.
