### ISSUE TITLE
DC Motor Not Working

### ISSUE THREAD

**Issue by bkannadassan** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#12]
Hi All,

   I tried following circuit, basically I want GPIO connection without any need of relay or speed control. But apparently attached circuit never worked. Am I missing something ?, can you please help me on the same..

I see only 2 circuit with motor present.
1) With Switch
2) With Relay

I don't want either, mine should basically start with just transitior.

rgds
Balaji Kamal Kannadassan
![whatsapp image 2019-01-20 at 19 04 35](https://user-images.githubusercontent.com/37536487/51440992-e7e94a80-1cf2-11e9-990a-70cae306092e.jpeg)
![whatsapp image 2019-01-20 at 19 04 22](https://user-images.githubusercontent.com/37536487/51440993-e881e100-1cf2-11e9-9d38-206e78d3c2e3.jpeg)

**Comment by bkannadassan** [comment]
Thanks buzzer worked, since you warned on the damage to raspberry pi. I am now testing first buzzer with external source. I see it not working, I see it working if instead of + I put in 5v and - I put in ground but not the same when I attach to + of battery and - of battery. Am I missing something ?.

-Balaji

**Comment by bkannadassan** [comment]
Hi,
   Thanks I took example from Chapter 6, now its working but apparently its always making sound even when I do on/off. It stops only when I do cleanup. Attaching circuit and code for your reference. Btw When I try attaching motor though its always making sound, I see it not working. Can you let me know solution for both ?.

-Balaji

![whatsapp image 2019-01-21 at 10 35 36](https://user-images.githubusercontent.com/37536487/51454159-5668ef80-1d69-11e9-8725-dfdb746c21f2.jpeg)
![whatsapp image 2019-01-21 at 10 36 00](https://user-images.githubusercontent.com/37536487/51454160-57018600-1d69-11e9-8021-55b60c715e6e.jpeg)
![whatsapp image 2019-01-21 at 10 42 10](https://user-images.githubusercontent.com/37536487/51454161-57018600-1d69-11e9-88a6-b6c6efdbc94c.jpeg)

**Comment by SuhaylZhao** [comment]
Hi,

1. The connection of the EC pole of the transistor is wrong. It should be exchanged.

2. The motor has the sound but does not work, may be not enough power. It is recommended that you use the power supply module. The positive (5V) is connected to the C pole of the transistor and the negative to the GND.

Please try it.

Thanks.
