### ISSUE TITLE
Softlight.py : error file not found line 13

### ISSUE THREAD

**Issue by bmaire28** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#15]
Hi, I get the follwing issue in Chapter 8 "Potentiometer & LED" :
pi@raspberrypi:~/freenove/ultimate/Code/Python_Code/08.1.1_Softlight/ python Softlight.py 
Traceback (most recent call last):
  File "Softlight.py", line 13, in <module>
    bus=smbus.SMBus(1)
FileNotFoundError: [Errno 2] No such file or directory

I've found SMBus can be set to 0 but doesn't solve the problem.

**Comment by SuhaylZhao** [comment]
Hi, 

Have you finished Chapter 7? There are some important installation steps in Chapter 7. Don't miss them.

If you still haven't solved the problem, please send your error screenshot to support@freenove.com

Thanks.
