### ISSUE TITLE
Instructions for installing Python Libs.

### ISSUE THREAD

**Issue by lonlandry** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#24]
I cannot find instructions or a way to install python libraries ADCDevice-1.0.2 & ADCDevice-1.0.3 I have tried usual pip and pip3 install instructions but ADCDevice-1.0.2 is not found.

**Comment by SuhaylZhao** [comment]
Hi,

In Chapter 7 of the tutorial, page 115,  you can find how to install the adcdevice library. 

![image](https://user-images.githubusercontent.com/3676296/93151690-29800200-f72f-11ea-95fe-3792cd449ac3.png)

Thanks!
