### ISSUE TITLE
Issue with command line

### ISSUE THREAD

**Issue by JakeJSW** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#25]
hi
I'm not sure where my issues should go but I need help with a command prompt. I am on the first tutorial labeled as blink. The issue that I'm having is when I type in cd ~/Freenove_Kit/Code/C_Code/01.1.1_Blink . The only message I get is "there is no such file or directory". I followed the above steps where I had to download the latest version of wiringpi and that all went smooth and updated. I looked through the files on the pi and have found the location of blink file. I'm not sure if its a corrupt file or if I'm doing something wrong. I've typed that line of code in like 10 times and received the same message ever time.

**Comment by SuhaylZhao** [comment]
Hi,

Did you rename this folder? Please send me a screenshot.
![image](https://user-images.githubusercontent.com/3676296/93847509-a97f0c80-fcd9-11ea-9ac4-251e07cc0275.png)

In addition, send your questions to support@freenove.com You can also get help.

Thanks！

**Comment by felix741** [comment]
python
