### ISSUE TITLE
The amazon store title said there were 434 pages of detailed instructions, is this the correct one?

### ISSUE THREAD

**Issue by NielAgi** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#26]
The amazon store title said there were 434 pages of detailed instructions https://www.amazon.de/-/nl/gp/product/B06W54L7B5/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
The tutorial.pdf only contains 314 pages.
Is this the correct repo for the Raspberry pi 4?

**Comment by SuhaylZhao** [comment]
Hi,

It is calculated as follows: 315(tutorial.pdf ) + 165(processing.pdf ) = 480 pages.  Both user manuals are updated over time, resulting in a change in the number of pages.

Thanks!

**Comment by NielAgi** [comment]
Gotcha

Thanks for the explanation.
