### ISSUE TITLE
Chapter 23 Infrared sensor should be connected to 5V and not 3.3V

### ISSUE THREAD

**Issue by ricardoV94** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#27]
I tried to follow the instructions on chapter 23 - Infrared Motion Sensor, but it was not working. The led kept turning on and off indefinitely. I did some research and found that the sensor needs an input voltage between 4.5 and 20 volts, and found this [Raspberry tutorial](https://www.freva.com/2019/05/21/hc-sr501-pir-motion-sensor-on-raspberry-pi/) that suggests the sensor should be connected to the 5v pin. In the tutorial pdf, however, you say that it should be connected to 3.3v. After changing it to 5v, the code worked flawlessly!

![image](https://user-images.githubusercontent.com/28983449/98464311-47fbfa00-21c2-11eb-919a-1b804cf5823f.png)

You should probably also tell people to adjust the time delay potentiometer to short responses (counter clockwise), as this will make the led more responsive (and it is probably what people expect to see at first)

**Comment by SuhaylZhao** [comment]
Hi,

Thank you for your advice, we will consider and fix this problem
