### ISSUE TITLE
I2CLCD turn backlight off

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#32]
https://github.com/Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi/blob/0535aee2f4d80174236b544fdf4962938ac8a5eb/Code/Python_Code/20.1.1_I2CLCD1602/I2CLCD1602.py#L24

`mcp.output(3,1)     # turn on LCD backlight`

Is used to turn the backlight on ... how do I actually turn the backlight off?

`mcp.output(3,0)` does not work

Or am I using the wrong pin number?

**Comment by DenzelChen** [comment]
Dear customer,
We just test it. Just modify it mcp.output(3,0)
Then run the code. The backlight will be turned off.
Have a nice day. :)
Sincerely,
Denzel
Freenove

**Comment by mariomurrent-softwaresolutions** [comment]
Okay, I'll try it again .. thx
