### ISSUE TITLE
Document supported Python versions

### ISSUE THREAD

**Issue by juho-jaakkola** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#4]
Might be good to document the supported version(s) somewhere.

Might even be worth considering to create a separate git branch for each supported version (in case parts of the code do not work on all versions). Although this would probably require also separating each programming language to it's own repository.

Just some food for thought.

**Comment by SuhaylZhao** [comment]
Hi, 

Thank you for your advice. Your idea is very good. At present, our code only supports Python2. We are also considering adding code that supports Python3. This is a big project. In addition, multi version support will make our maintenance work more difficult, so we will consider this matter carefully.
