### ISSUE TITLE
I2CLCD1602.py cannot find the LCD device at address 0x27 or 0x3f

### ISSUE THREAD

**Issue by ryanzzz** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#47]
When doing lab 20.1.1 for I2CLCD1602, I encountered an error: I2C address 0x27 or 0x3f not found.
It was strange because the I2CLCD was identified with address 0x3f using the i2c_tools, but failed to be identified with your code.

Here are a few screenshots:

1. The I2CLCD could be identified with i2c_tools. You can see the 3f address in the scanned table:
<img width="563" alt="image" src="https://github.com/user-attachments/assets/b8c9cb0b-8147-41a3-b4fb-7de9eb548155">

2. However, when the I2CLCD1602.py code was run, the error was thrown:
<img width="351" alt="image" src="https://github.com/user-attachments/assets/1e079144-9257-4c19-b7dd-6178d9603cb7">

3. When I debugged the variables, the i2c_list is empty. It seems the python code failed to identify the LCD device:
<img width="147" alt="image" src="https://github.com/user-attachments/assets/21faf3be-b704-46d0-b122-874877c16e58">

Additional background:
- I am using Raspberry Pi 4B, and the latest Python codes provided by Freenove using the GPIO Zero library.
- I was not the only person who encountered this error. We have a study group of seven students all seeing the same issue today. We have a mix bag of LCD's, some with address 0x27 while others with address 0x3f.
- I used the old codes provided by Freenove using the traditional GPIO library a few years ago, and didn't see this issue at that time. I am not sure what changes between the GPIO to GPIO Zero conversion that caused the issue.

**Comment by Zhentao-Lin** [comment]
i2c_list uses i2c_scan to obtain the lcd1602 address, the i2c_scan function also uses the i2cdetect-y 1 command to obtain the lcd1602 address. Obviously, although you can successfully obtain the address of Lcd1602 in the terminal with i2cdetect-y 1, it cannot be obtained in the code.
In addition, I installed the latest version of the system on my Raspberry PI 3,4,5, and then downloaded this repository, I can use lcd1602 normally.

**Comment by Zhentao-Lin** [comment]
This is not caused by the gpiozero library.

**Comment by ryanzzz** [comment]
Yes, I can see that LCD1602.py uses this line of code to populate the i2c_list:  `cmd = "i2cdetect -y 1 |awk \'NR>1 {$1=\"\";print}\'"`. However, I am confused why the i2c_list is an empty list while the `i2cdetect -y 1` command in the terminal can obtain the address. 
Again, it was not just me but several instances of the same issue that were found on both Pi 3 and 4 and with both 0x27 and 0x3f LCD types. All of us purchased the Freenove Ultimate Starter kit from Amazon without any modification of the parts.

**Comment by Zhentao-Lin** [comment]
def i2c_scan(self):
        cmd = "i2cdetect -y 1 |awk \'NR>1 {$1=\"\";print}\'"
        result = subprocess.check_output(cmd, shell=True).decode()
        print(result)
        result = result.replace("\n", "").replace(" --", "")
        i2c_list = result.split(' ')
        return i2c_list
Add a line to the code, print(result), and see if you get the raw data.

**Comment by ryanzzz** [comment]
I added the print line in LCD1602.py and then run I2CLCD1602.py, and the code errored out before printing.
<img width="347" alt="image" src="https://github.com/user-attachments/assets/7d694bad-48cf-4f5f-b2ec-c8679ccea353">
I noticed that the code tried to find `i2cdetect` command in `/bin/sh` as shown in the screenshot. However, my `i2cdetect` is located at `usr/sbin`. Could this be the cause? If so, how do I modify the code so that it searches the `usr/sbin` path?
<img width="538" alt="image" src="https://github.com/user-attachments/assets/122cef55-743e-424b-b98a-87838731d645">

**Comment by Zhentao-Lin** [comment]
Try modifying the code to see if it works.
def i2c_scan(self):
    cmd = "/usr/sbin/i2cdetect -y 1 | awk 'NR>1 {$1=\"\";print}'"
    result = subprocess.check_output(cmd, shell=True).decode()
    print(result)
    result = result.replace("\n", "").replace(" --", "")
    i2c_list = result.split(' ')
    return i2c_list

**Comment by ryanzzz** [comment]
Fantastic news! The modification you suggested worked perfectly. The key was setting the correct path for `i2cdetect`. 

Would it be possible to update the ICD code in the future to automatically detect the path? Alternatively, is there a way for me to manually specify the path for `i2cdetect`?  We installed `i2c-tools` using the command `sudo apt-get install i2c-tools` as instructed in the tutorial.

Thank you again for your prompt assistance in resolving this issue!

**Comment by Zhentao-Lin** [comment]
As long as i2cdetect is in your system's environment variable PATH, or you specify the correct full path in your code, your code should work fine.

If the environment variable PATH does not contain /usr/sbin, the i2cdetect command may not be found. You can check this by printing the PATH environment variable:
import os  
print(os.getenv('PATH'))

If /usr/sbin is not in PATH, you can add it to PATH before executing the command, or call i2cdetect directly in your code using the full path.
