### ISSUE TITLE
Typo in chapter 13 ( Relay & Motor)

### ISSUE THREAD

**Issue by mikebern** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#8]
Tutorial, page 143 (python code):

 "We need to use the map () subfunction mapping the difference value to range of **0-255**. "

Should be:

"We need to use the map () subfunction mapping the difference value to range of **0-100**. "

Because in the code we have :
p.start(mapNUM(abs(value),0,128,0,**100**))

**Comment by SuhaylZhao** [comment]
Yes， You are right! We will modify this mistake as soon as possible. Thank you.

**Comment by mikebern** [comment]
Glad I was able to help. Cheers!

**Comment by SuhaylZhao** [comment]
We have modified this mistake in the last update, so I will close this issue.

Thanks.
